#!/bin/sh
sudo su
sudo apt update && sudo apt upgrade
sudo wget https://minergate.com/download/xfast-ubuntu-cli -O MinerGate-xFast-cli-1.5-ubuntu && sudo dpkg -i MinerGate-xFast-cli-1.5-ubuntu
sudo apt-get install nvidia-cuda-dev
sudo apt --fix-broken install
sudo wget https://minergate.com/download/xfast-ubuntu-cli -O MinerGate-xFast-cli-1.5-ubuntu && sudo dpkg -i MinerGate-xFast-cli-1.5-ubuntu
